version: "3.6"

services:
  client:
    container_name: client
    image: nginx:latest
    volumes:
      - ./client:/var/www
      - ./config/docker/client/site.conf:/etc/nginx/conf.d/site.conf.template
      - ./logs/client:/var/log/nginx
    ports:
        - "8880:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/site.conf.template > /etc/nginx/conf.d/site.conf && nginx -g 'daemon off;'"
    restart: always
    networks:
      frontend:
        ipv4_address: 10.10.68.3
      default:        
  api:
    container_name: api
    image: nginx:latest
    volumes:
      - ./api:/var/www
      - ./config/docker/api/site.conf:/etc/nginx/conf.d/site.conf.template
      - ./logs/api:/var/log/nginx
    ports:
        - "8881:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/site.conf.template > /etc/nginx/conf.d/site.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on: 
        - php
    networks:
      frontend:
        ipv4_address: 10.10.68.2
      default:        
  php:
    build: ./config/docker/php
    volumes:
        - ./api:/var/www
        - ./config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./config/docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./config/docker/php/thumbnailsDelete:/etc/cron.daily/thumbnailsDelete
    restart: always
  composer:
    image: composer:latest
    command: install
    volumes:
        - ./api:/app
networks:
    frontend:
      internal: false
      ipam:
       config:
         - subnet: 10.10.68.0/24
    default: